# frozen_string_literal: true

require "spec_helper"

describe "PaperTrail MySQL compatibility patch" do
  before do
    # Paper Trail's JSON query methods check the column type and only run the
    # JSON code path for :json/:jsonb columns. Stub the column type so we can
    # verify the SQL generated by the patched json methods.
    json_column = instance_double(ActiveRecord::ConnectionAdapters::Column, type: :json)
    allow(PaperTrail::Version).to receive(:columns_hash).and_return(
      PaperTrail::Version.columns_hash.merge("object_changes" => json_column)
    )
  end

  describe "where_object_changes" do
    it "generates LIKE instead of ILIKE for MySQL compatibility" do
      relation = PaperTrail::Version.where_object_changes(code: "flat80")
      generated_sql = relation.to_sql

      expect(generated_sql).to include("LIKE")
      expect(generated_sql).not_to include("ILIKE")
    end
  end

  describe "where_object_changes_to" do
    it "generates LIKE instead of ILIKE for MySQL compatibility" do
      relation = PaperTrail::Version.where_object_changes_to(code: "flat90")
      generated_sql = relation.to_sql

      expect(generated_sql).to include("LIKE")
      expect(generated_sql).not_to include("ILIKE")
    end
  end

  describe "where_object_changes_from" do
    it "generates LIKE instead of ILIKE for MySQL compatibility" do
      relation = PaperTrail::Version.where_object_changes_from(code: "flat80")
      generated_sql = relation.to_sql

      expect(generated_sql).to include("LIKE")
      expect(generated_sql).not_to include("ILIKE")
    end
  end
end
